site_name: LuminoDocs
theme:
  name: material
  icon:
    logo: material/wizard-hat
  favicon: images/favicon.ico
  font:
    text: Montserrat
    code: Red Hat Mono

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.anotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue grey
      accent: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: blue grey
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/YoooKai
      name: Kai
    - icon: fontawesome/brands/github-alt
      link: https://github.com/JVC0
      name: Joseph

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2025 <a href="https://github.com/YoooKai" target="_blank" rel="noopener">Kai</a> &amp; 
  <a href="https://github.com/JVC0" target="_blank" rel="noopener">Joseph</a>
